name: learmond
description: The Learmond Corporation's official flutter package.
version: 0.0.0
homepage: https://thelearmondcorporation.com
repository: https://github.com/thelearmondcorporation/learmond

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  args: ^2.7.0
  mason_logger: ^0.3.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
