name: learmond
description: The Learmond Corporation's official CLI tool. Includes learmond_flutter.
version: 0.1.1
homepage: https://github.com/thelearmondcorporation/learmond
repository: https://github.com/thelearmondcorporation/learmond.git

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  args: ^2.7.0
  mason_logger: ^0.3.3
  crypto: ^3.0.7
  learmond_flutter: ^0.0.1+2

executables:
  learmond: learmond.dart

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
